### ISSUE TITLE
Code keeps crashing

### ISSUE THREAD

**Issue by madgore** [bdalpe/RADIUS-to-Okta-MFA#1]
When we use the app, after an authentication, which is successful, the code errors out. See below. Any idea what might be causing this?
![image](https://user-images.githubusercontent.com/70166196/91077373-f2766f00-e60e-11ea-9b71-3de70f93b94c.png)

**Comment by bdalpe** [comment]
Hi @madgore. Thanks for raising the issue.

I think there's a missing key-value mapping in the dictionary file. Can you put this at line 118 in `dictionary`?

```
ATTRIBUTE   Tunnel-Client-Endpoint  66  string
```

Please let me know if that resolves the issue.

**Comment by madgore** [comment]
Thank you very the really rapid response. Awesome little tool btw. That resolved the issue and now it stays open. We have a "Dropping packet from unknown host" coming up, but seems stable, thank you.

**Comment by bdalpe** [comment]
Thanks @madgore! Glad it's working and that you like it.
