### ISSUE TITLE
Functionality impact in case of Okta API change / Python modules gets updated

### ISSUE THREAD

**Issue by sandypatel1986** [bdalpe/RADIUS-to-Okta-MFA#117]
Hi Brendan,

Myself Sandipkumar from India. I was looking for Okta MFA integration with Microsoft Remote desktop gateway and I found this very useful posts.

https://github.com/bdalpe/RADIUS-to-Okta-MFA

https://support.okta.com/help/s/question/0D51Y00008JNftqSAD/tutorial-okta-mfa-push-authentication-on-microsoft-remote-desktop-gateway?language=en_US

I have successfully integrated my environment using above method and github script. Now I am planning to roll out the same in production environment. But my question is that what if Okta changes something with their API and this script stops working ? I can see it is making some kind of API call with Okta.

My second question is that there are some python modules like certifi, idna, six etc. Now for an example, if certifi modules gets updated from version 2 to version 3, will it impact the integration ? 

If the Linux machine OS gets updated will it impact the environment ?

Can you please let us know Brendan ?

Thanks,
Sandipkumar Patel.

**Comment by sandypatel1986** [comment]
Hi Brendan,
Can you please provide an update here ? We are eagerly waiting for it.

Thanks,
Sandipkumar Patel.

**Comment by bdalpe** [comment]
Hi @sandypatel1986, this project is released under an [MIT license](https://en.wikipedia.org/wiki/MIT_License). There is no implied or expressed support and you are free to use it at your own risk.

> But my question is that what if Okta changes something with their API and this script stops working ?

Considering Okta has over 17000 customers and many integrations relying on the APIs, I doubt that there will be any changes to the core APIs used in this project. This project is 5 years old and I have not had to make any changes to the Okta API calls. If Okta does change the APIs for some reason, I would welcome an Issue or Pull Request to update this code.

> Now for an example, if certifi modules gets updated from version 2 to version 3, will it impact the integration ?

[Dependabot](https://github.com/bdalpe/RADIUS-to-Okta-MFA/blob/master/.github/dependabot.yml) is configured to update the Python dependencies used in this project. There are unit tests run on each Pull Request to ensure the updated dependencies are compatible with the codebase. (see [tests.py](https://github.com/bdalpe/RADIUS-to-Okta-MFA/blob/master/tests.py))

> If the Linux machine OS gets updated will it impact the environment ?

I would recommend that you run the code inside a Docker container to ensure the code/service is separate from the OS. You should follow general DevOps principles and test OS updates in a staging environment before promoting them to production. I cannot account for all environmental scenarios.
