### ISSUE TITLE
Rate Limit?

### ISSUE THREAD

**Issue by kjake** [bdalpe/RADIUS-to-Okta-MFA#14]
Thanks for putting this together - it is my preferred way to 2FA Remote Desktop!

I've toyed with my RD Gateway's Network Policy Server to increase timeouts, but I still have users get into a situation where they keep getting Push Notifications from Okta Verify - and most of the time, the RD session doesn't connect.  I think this is because this RADIUS sever is sending too many requests too close together for the same user and the connection attempt isn't really getting approved.

Do you think there would be a way to do user-level filtering within the RADIUS server to reject requests coming in too close, or back-to-back?  I'm not really versed in Python, or I'd try this out myself and submit a PR.

**Comment by bdalpe** [comment]
Hi @kjake,

Thanks for raising the issue. I suspected this was occurring when I originally developed this utility, but good to have confirmation.

I think it should be pretty easy to change the Okta polling logic to wait until the original verification request has been completed if future requests are received from the NPS. Just need to move a few items around in `okta.py`

I'll try to get to this in the next couple of days.
