### ISSUE TITLE
No radius listener

### ISSUE THREAD

**Issue by LucusSTO** [bdalpe/RADIUS-to-Okta-MFA#2]
Hi,

I'm trying to make your tool work because I could not figure out the Okta radius server agent and Okta themselves do not seem to know how to make it work with RD gateway either.

I installed an Ubuntu VM (on hyper-v) (latest desktop version, all updates done), python3, followed the simple instructions but the python script seems to hang at startup, it stays at Starting server and no listener is created (port 1812). I run it as admin/root user, all files are in a single folder, did not have any errors for the requirements.

Any idea?

Thanks.

**Comment by bdalpe** [comment]
Hi @LucusSTO,

Just wanted to check that you also modified the environment variables in the `run.sh` script to their appropriate settings.

If you see this when running the program, then everything is good:
```
./run.sh
2020-12-01 09:20:37,600 [INFO    ] Starting server...
```

It does look like the process hangs, but it's waiting for connections. You'll need to daemonize the process however you see fit.

Radius uses UDP on port 1812. Can you verify with a tool like `netstat` or `ss` that 1812 is listening when the program runs?

```
sudo netstat -tulpn | grep 1812
```

For testing, here's a Python script you can use:

```python
from pyrad.client import Client
from pyrad.dictionary import Dictionary
import pyrad.packet
from secrets import token_hex

USERNAME = "your_okta_username"
PASSWORD = "your_okta_password"
RADIUS_SECRET = b"$upers3cret"

srv = Client(server="localhost", secret=RADIUS_SECRET, dict=Dictionary("dictionary"))

# create request
req = srv.CreateAuthPacket(code=pyrad.packet.AccessRequest, User_Name=USERNAME, NAS_Identifier="localhost")
req["User-Password"] = req.PwCrypt(PASSWORD)
req["Proxy-State"] = token_hex(8).encode("ascii")

# send request
reply = srv.SendPacket(req)

if reply.code == pyrad.packet.AccessAccept:
    print("access accepted")
else:
    print("access denied")

print("Attributes returned by server:")
for i in reply.keys():
    print("%s: %s" % (i, reply[i]))
```

**Comment by LucusSTO** [comment]
Thanks for your answer Brendan,

I will look into it this afternoon. For the listener on 1812, as I wrote in my original post, it's not created.

**Comment by LucusSTO** [comment]
Hi Brendan,

I tested a couple of things yesterday but still can't make the listener work. Is there any way to log the starting part? I see the [INFO    ] Starting server... but still no listener. Redownloaded, checked permissions, made a new Okta api key, typed all parameters manually in run.sh in case of copy/pasteinvalid ghost  character. 

I can try reinstalling a new Ubuntu VM from scratch and start over just in case but the install i'm using now is also freshly installed just for that with nothing more than the requirements.

Thanks for your help.

**Comment by LucusSTO** [comment]
I tested your client test script anyway, and of course:

inex@inex-ubuntu1:/oktarad$ python3 test.py
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    reply = srv.SendPacket(req)
  File "/usr/local/lib/python3.8/dist-packages/pyrad/client.py", line 180, in SendPacket
    return self._SendPacket(pkt, self.authport)
  File "/usr/local/lib/python3.8/dist-packages/pyrad/client.py", line 168, in _SendPacket
    raise Timeout
pyrad.client.Timeout

**Comment by LucusSTO** [comment]
Maybe I should try another distro? I used Ubuntu since I know it works well under HyperV (pv drivers are up to date). What do you use?


Thanks.

**Comment by bdalpe** [comment]
@LucusSTO, I was able to replicate your issue. I will push a commit with the fix today.

In `server.py` on line 75, the following code needs to be changed:

```
-    srv.BindToAddress("")
+    srv.BindToAddress("0.0.0.0")
```

Once the quad zero address is added, you should see the server listening on 1812 when you run the server script.

**Comment by LucusSTO** [comment]
Thanks Brandan, I will make the change and test it.


Luc St-Onge
Ordinateurs STO
www.sto.qc.ca
lstonge@sto.qc.ca

Le 2 déc. 2020 10:53, Brendan Dalpe <notifications@github.com> a écrit :

@LucusSTO<https://github.com/LucusSTO>, I was able to replicate your issue. I will push a commit with the fix today.

In server.py on line 75, the following code needs to be changed:

-    srv.BindToAddress("")
+    srv.BindToAddress("0.0.0.0")


Once the quad zero address is added, you should see the server listening on 1812 when you run the server script.

**Comment by LucusSTO** [comment]
It works fine now.

Have a nice day.
