### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by citnadxela** [bdalpe/RADIUS-to-Okta-MFA#25]
I'm currently on this step (following https://support.okta.com/help/s/question/0D51Y00008JNftqSAD/tutorial-okta-mfa-push-authentication-on-microsoft-remote-desktop-gateway?language=en_US):

"Once this is completed installing, just run the command /bin/sh run.sh and leave the terminal open. It will be blank, and you will see nothing."

After running run.sh, I'm met wi/ this & not sure where I went wrong as I'm confident I've followed every step 100% correctly up until now:

`Traceback (most recent call last):
  File "server.py", line 87, in <module>
    run()
  File "server.py", line 78, in run
    srv.BindToAddress("0.0.0.0")
  File "/usr/local/lib/python3.6/site-packages/pyrad/server.py", line 139, in BindToAddress
    authfd.bind((address, self.authport))
OSError: [Errno 98] Address already in use`

Just by doing basic research, I believe this happens because it's trying to run service at the same port and there is an already running application?  But not really sure, so any help wi/ this will greatly be appreciated.

**Comment by bdalpe** [comment]
Hi @citnadxela, it sounds like there is already another process bound to the RADIUS port. If you run `sudo netstat -tulpn` what process is the output? Is there something already listening on port 1812?

**Comment by citnadxela** [comment]
![image](https://user-images.githubusercontent.com/40772046/130266287-40de7e29-e86c-458d-8981-139e659d5c84.png)

Hi @bdalpe.  Thanks for the reply.  The output is above.

**Comment by bdalpe** [comment]
If you look at the bottom of the screenshot, there's a `java` process (pid 3295) running listening on with local address of `:::1812`. Either you need to stop this process or run the script on a new box.

**Comment by citnadxela** [comment]
Ah I i didn't see that initially !!  So stopping this process, then running the script would resolve it?  Running the script on a new box isn't really an option because I was given this box as it was created solely for this Okta RADIUS project.  What would you recommend I do in my case?

**Comment by citnadxela** [comment]
Hi @bdalpe, just wanted to follow up & see what you would recommend me doing since I can't really run the script on a new box.  Let me know.  Appreciate your help thus far.

**Comment by bdalpe** [comment]
@citnadxela I added two environment variables: `RADIUS_AUTH_PORT` and `RADIUS_ACCT_PORT` that you can define in the `run.sh` script or your Docker environment variables to let the server run on a different port of your choosing.
