### ISSUE TITLE
samAccountName search is broken

### ISSUE THREAD

**Issue by Anonymousdog** [bdalpe/RADIUS-to-Okta-MFA#35]
When running with export `OKTA_USE_SAMACCOUNTNAME=true`, the as-written okta.py script throws an error when solicited with an NPS RADIUS query:
`dler
    raise HTTPError(resp.status_code, resp.json(), response=resp)
requests.exceptions.HTTPError: [Errno 400] {'errorCode': 'E0000031', 'errorSummary': 'Invalid search criteria.', 'errorLink': 'E0000031', 'errorId': 'oaegJip6GiSSwK1jGSqvTSmAA', 'errorCauses': [{'errorSummary': 'Invalid search attribute.'}]}
`
After doing some Okta API research and running a ton of test queries against our account, I find that List Users using a search will not accept any profile attributes that aren't part of the Okta profile. So, this AD attribute, while shown in the admin UI's user profiles on accounts linked to AD, the API returns an error when searching for any of those AD attributes.

What you CAN do is create an Okta profile custom attribute named 'samAccountName', map the AD 'samAccountName' to it in the profile mappings between AD and Okta. Then, this script works as desired....like butta'.

Thanks,
AnonymousDog

**Comment by bdalpe** [comment]
Going to close this as it's something I'm not going to change.
